//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db_First_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int id { get; set; }
        public string studentName { get; set; }
        public string gender { get; set; }
        public string standard { get; set; }
        public string section { get; set; }
        public string hobbies { get; set; }
        public string subjects { get; set; }
        public Nullable<int> marks1 { get; set; }
        public Nullable<int> marks2 { get; set; }
        public Nullable<int> marks3 { get; set; }
        public Nullable<long> total { get; set; }
    }
}
